contexts:
- context: arn:aws:eks:eu-west-1:177734401659:cluster/EksTicketDevV1
  namespaces:
  - namespace: d4i
    pods:
    - service: batch
      port: 8080
    - service: booking-order-api
      port: 8081
    - service: client-api
      port: 8082
    - service: globick-web
      port: 8083
    - service: identity-server
      port: 8084
    - service: notification-api
      port: 8085
    - service: product-api
      port: 8086
    - service: search-engine-api
      port: 8087
    - service: storage-api
      port: 8088
    - service: supplier-engine-api
      port: 8089
    - service: translator-api
      port: 8090
    - service: trip-gateway
      port: 8091
